openapi: 3.0.0
info:
  version: 0.0.1
  title: fronterra-core-api

servers:
  - url: 'http://api.example.com/v1' # TODO: update
    description: Production server
  - url: 'http://api.example.com/v1/testing' # TODO: update
    description: Staging server
  - url: 'http://localhost:4000'
    description: Development server

paths:
  /media:
    post:
      summary: Uploads file to server.
      # description: Optional extended description could go here, MD supported
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mediaId
                - reportId
              properties:
                mediaId:
                  type: string
                reportId:
                  type: string
          
          multipart/form-data:
            schema:
              type: object
              required:
                - mediaFile
              properties:
                mediaFile:
                  type: string
                  format: binary

      responses:
        201:
          description: Successful request, resource was added on server
        412: 
          description: Error, invalid inputs


  /reports:
    get:
      summary: Returns an array of reports
      # more needed

    post:
      summary: Creates a new report on server
      # more needed

components:
  schemas:
    Media:
      type: object
      required:
        - mediaId
        - reportId
        - mediaFiler
      properties:
        mediaId:
          type: string
        reportId:
          type: string
        mediaFile:
          type: string
          format: binary
    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string