openapi: 3.0.0
info:
  version: 0.0.1
  title: fronterra-core-api

servers:
  - url: 'http://api.example.com/v1' # TODO: update
    description: Production server
  - url: 'http://api.example.com/v1/testing' # TODO: update
    description: Staging server
  - url: 'http://localhost:4000'
    description: Development server

paths:
  /media:
    post:
      summary: Uploads file to server.
      # description: Optional extended description could go here, MD supported

      parameters:
        - in: query
          name: reportId
          required: true
          schema:
            type: string
          description: the id of an associated report object
        - in: query
          name: mediaId
          required: true
          schema:
            type: string
          description: The id assigned to mediaFile 

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - mediaFile
              properties:
                mediaFile:
                  type: string
                  format: binary

      responses:
        201:
          description: Successful request, resource was added on server
        412: 
          description: Error, invalid inputs


  /reports:
    get:
      summary: Returns an array of reports
      # more needed
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            # needs a default property that defaults to one
          description: Specifies the number of a page to recieve
        - in: query
          name: size
          schema:
            type: integer
            # needs a default property that defaults to 25 or something
          description: Specifies the maximum number of reports to return per page


      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
        500:
          descriptions: Unexpected error.


              

  /reports/{reportId}:
    get:
      summary: Returns a single report object
      parameters:
        - in: path
          name: reportId   # Note the name is the same as in the path
          required: true
          schema:
            type: string
      
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  reportId:
                    type: string
                    description: report id string
                  description:
                    type: string
                    description: A description of the pollution observed
                  pollutionType:
                    type: string
                    description: Category of pollution
                  location:
                    type: string
                    description: coordinates of the report
                  mediaIds:
                    type: array
                    description: Array of media ids
        404:
          description: A user with the specified ID was not found.
        500:
          description: Unexpected error.
                  

      # more needed


    post:
      summary: Creates a new report on server
      # more needed

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - description
                - location
                - locationType
                - datetime
                - datetimeType
                - pollutionType
                - mediaIds
                - mediaUploadSuccesses
                - mediaUploadFailures

              properties:
                description:
                  type: string
                location:
                  type: string
                locationType:
                  type: string
                datetime:
                  type: string
                datetimeType:
                  type: string
                pollutionType:
                  type: string
                mediaIds:
                  type: array
                mediaUploadSuccesses:
                  type: array
                mediaUploadFailures:
                  type: array

      responses:
        201:
          description: Successful request
        500: 
          description: Unexpected error.
              


components:
  schemas:
    Report:
      type: object
      required:
        - description
        - location
        - locationType
        - datetime
        - datetimeType
        - pollutionType
        - mediaIds
      properties:
        mediaId:
          type: string
        reportId:
          type: string
        mediaFile:
          type: string
          format: binary
    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string